name: What is the build id?
run-name: 빌드 버전 네이밍 결정하기

on: workflow_dispatch

jobs:
  print:
    name: print build id
    runs-on: ubuntu-latest
    steps:
      - name: Github Run ID 값을 이용?
        run: |
          echo "Github Run ID: ${{ github.run_id }}"
          echo "Github Run Number: ${{ github.run_number }}"