name: condition-test
run-name: job 단위 조건문 동작 여부 테스트

on: workflow_dispatch

jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    outputs:
        CACHE_HIT: ${{ steps.prebuild.outputs.CACHE_HIT }}
    steps:
      - name: prebuild
        id: prebuild
        run: |
          echo "CACHE_HIT=true" >> $GITHUB_OUTPUT

  print1:
    name: print if not true
    needs: [prebuild]
    if: needs.prebuild.outputs.CACHE_HIT != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: CACHE HIT 가 true 가 아닐 때에만 동작
        run: |
          echo "CACHE HIT FALSE: ${{ needs.prebuild.outputs.CACHE_HIT }}"

  print2:
    name: print if true
    needs: [prebuild]
    if: needs.prebuild.outputs.CACHE_HIT == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: CACHE HIT 가 true 일 때에만 동작
        run: |
          echo "CACHE HIT TRUE: ${{ needs.prebuild.outputs.CACHE_HIT }}"
