name: Github File Download Test
run-name: 캐시에 저장된 파일을 다운로드해서 읽어올 수 있는가?

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 다운로드할 파일 이름
        type: string
        required: true

jobs:
  build:
    name: 파일 다운로드
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.file-name }}
          path: ${{ github.workspace }}/${{ github.event.inputs.file-name }}

      - name: Print downloaded file
        run: |
          echo "Downloaded file contents:"
          cat ${{ github.workspace }}/${{ github.event.inputs.file-name }}

#      - name: Download output file from cache
#        uses: actions/cache@v2
#        with:
#          path: ${{ github.workspace }}/output
#          key: ${{ runner.os }}-output-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-output-
#            ${{ runner.os }}-
#            ${{ runner.os }}