name: Github File Download Test
run-name: 캐시에 저장된 파일을 다운로드해서 읽어올 수 있는가?

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 다운로드할 파일 이름
        type: string
        required: true

jobs:
  build:
    name: 파일 다운로드
    runs-on: ubuntu-latest
    steps:
      - name: Download output file from cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ github.event.inputs.file-name }}

      - name: Print output file
        working-directory: ${{ github.workspace }}
        run: |
          ls -al
          echo "Print output file"
          cat ${{ github.event.inputs.file-name }}