name: Github File Download Test
run-name: 캐시에 저장된 파일을 다운로드해서 읽어올 수 있는가?

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 다운로드할 파일 이름
        type: string
        required: true

jobs:
  build:
    name: 파일 다운로드
    runs-on: ubuntu-latest
    steps:
      - name: Download output file from cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/output
          key: ${{ runner.os }}-${{ github.event.inputs.file-name }}

      - name: Print output file
        working-directory: ${{ github.workspace }}
        run: |
          ls -al
          echo "Print output file"
#          cat ${{ github.event.inputs.file-name }}

      - name: Print if cache exists
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "캐시 존재함"

      - name: Print if cache not exists
        if: steps.cache.outputs.cache-hit == 'false'
        run: |
          echo "캐시 존재하지 않음"