name: Github Action Version Rollback Test
run-name: Github Action 버전 롤백 테스트

permissions: write-all

on:
  workflow_dispatch:
      inputs:
        version:
            description: 롤백할 버전
            type: string
            required: true

jobs:
  rollback:
    name: 애플리케이션 버전 롤백
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 현재 커밋 확인
        run: |
          git tag
          git checkout tags/${{ github.event.inputs.version }}
          git log