name: Github Action Version Upgrade Test
run-name: Github Action 버전 업그레이드 테스트

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      target-version:
        description: 업그레이드할 버전
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
        default: patch

jobs:
  upgrade-version:
    name: 애플리케이션 버전 업그레이드
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: 버전 업그레이드 후 커밋 & 푸시
        run: |
          OLD_VERSION=$(cat version)
          chmod +x ./upgrade-version.sh
          ./upgrade-version.sh ${{ github.event.inputs.target-version }}
          NEW_VERSION=$(cat version)
          
          MESSAGE="버전 업그레이드: $OLD_VERSION → $NEW_VERSION"
          echo $MESSAGE

          echo "user name: $(git log -n 1 --pretty=format:%an)"
          echo "user email: $(git log -n 1 --pretty=format:%ae)"
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          
          git commit -am "$MESSAGE"
          git tag -a $NEW_VERSION -m "$MESSAGE"
          git push origin main --follow-tags -f